// All users data - Teachers and Students
const users = [
  // Admin
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@college.edu',
    password: 'admin123',
    role: 'admin',
    department: 'Administration'
  },
  
  // Teachers from CST Department
  { id: 'T1', name: 'Dr. Devanshu Tiwari', email: 'devanshu.tiwari@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'DT001' },
  { id: 'T2', name: 'Dr. Tejaswita Mishra', email: 'tejaswita.mishra@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'TM002' },
  { id: 'T3', name: 'Dr. Kuldeep Tiwari', email: 'kuldeep.tiwari@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'KT003' },
  { id: 'T4', name: 'Dr. Gulshan Som', email: 'gulshan.som@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'GS004' },
  { id: 'T5', name: 'Mr. Kuldeep K. Swarnkar', email: 'kuldeep.swarnkar@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'KS005' },
  { id: 'T6', name: 'Dr. Barkha Tiwari', email: 'barkha.tiwari@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'BT006' },
  { id: 'T7', name: 'Dr. Suchitra Agrawal', email: 'suchitra.agrawal@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'SA007' },
  { id: 'T8', name: 'Mr. Utkarsh Sharma', email: 'utkarsh.sharma@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'US008' },
  { id: 'T9', name: 'Mr. Manoj Kumar', email: 'manoj.kumar@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'MK009' },
  { id: 'T10', name: 'Dr. Shradha Dubey', email: 'shradha.dubey@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'SD010' },
  { id: 'T11', name: 'Ms. Aditi Samadiya', email: 'aditi.samadiya@college.edu', password: 'teacher123', role: 'teacher', department: 'CST', employeeId: 'AS011' },
  
  // Students BTTC25O1002 to BTTC25O1076
  { id: 'S1002', name: 'AAYUSH DEHARIYA', email: 'aayush.dehariya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1002', enrollmentNo: 'BTTC25O1002' },
  { id: 'S1003', name: 'ABHAY SINGH CHAUHAN', email: 'abhay.chauhan@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1003', enrollmentNo: 'BTTC25O1003' },
  { id: 'S1004', name: 'ADITYA KUMAR PATEL', email: 'aditya.patel@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1004', enrollmentNo: 'BTTC25O1004' },
  { id: 'S1005', name: 'AGAM SHARMA', email: 'agam.sharma@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1005', enrollmentNo: 'BTTC25O1005' },
  { id: 'S1006', name: 'AJAY KUMAR BAIS', email: 'ajay.bais@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1006', enrollmentNo: 'BTTC25O1006' },
  { id: 'S1007', name: 'AJAY MEENA', email: 'ajay.meena@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1007', enrollmentNo: 'BTTC25O1007' },
  { id: 'S1008', name: 'AJAY YADAV', email: 'ajay.yadav@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1008', enrollmentNo: 'BTTC25O1008' },
  { id: 'S1009', name: 'AKSHI GALAV', email: 'akshi.galav@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1009', enrollmentNo: 'BTTC25O1009' },
  { id: 'S1010', name: 'AMOGH AMEYE', email: 'amogh.ameye@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1010', enrollmentNo: 'BTTC25O1010' },
  { id: 'S1011', name: 'AMRITA BIGHANE', email: 'amrita.bighane@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1011', enrollmentNo: 'BTTC25O1011' },
  { id: 'S1012', name: 'ANGEL LAL', email: 'angel.lal@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1012', enrollmentNo: 'BTTC25O1012' },
  { id: 'S1013', name: 'ANSHIKA BANSAL', email: 'anshika.bansal@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1013', enrollmentNo: 'BTTC25O1013' },
  { id: 'S1014', name: 'ANTRIKSH YADAV', email: 'antriksh.yadav@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1014', enrollmentNo: 'BTTC25O1014' },
  { id: 'S1015', name: 'ANVESH KUMAR', email: 'anvesh.kumar@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1015', enrollmentNo: 'BTTC25O1015' },
  { id: 'S1016', name: 'ARPIT CHAKRAVARTY', email: 'arpit.chakravarty@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1016', enrollmentNo: 'BTTC25O1016' },
  { id: 'S1017', name: 'ARPIT PATEL', email: 'arpit.patel@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1017', enrollmentNo: 'BTTC25O1017' },
  { id: 'S1018', name: 'ARUNIM RICHHARIYA', email: 'arunim.richhariya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1018', enrollmentNo: 'BTTC25O1018' },
  { id: 'S1019', name: 'ARYAN DINESH BHADOREEYA', email: 'aryan.bhadoreeya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1019', enrollmentNo: 'BTTC25O1019' },
  { id: 'S1020', name: 'ARYAN RANA', email: 'aryan.rana@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1020', enrollmentNo: 'BTTC25O1020' },
  { id: 'S1021', name: 'ARYAN SITOLE', email: 'aryan.sitole@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1021', enrollmentNo: 'BTTC25O1021' },
  { id: 'S1022', name: 'ASTHA JAIN', email: 'astha.jain@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1022', enrollmentNo: 'BTTC25O1022' },
  { id: 'S1023', name: 'ATIKSH PATEL', email: 'atiksh.patel@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1023', enrollmentNo: 'BTTC25O1023' },
  { id: 'S1024', name: 'CHARCHIT THAKUR', email: 'charchit.thakur@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1024', enrollmentNo: 'BTTC25O1024' },
  { id: 'S1025', name: 'DAKSHYA MANGROLIA', email: 'dakshya.mangrolia@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1025', enrollmentNo: 'BTTC25O1025' },
  { id: 'S1026', name: 'DEVANSH NARWARIA', email: 'devansh.narwaria@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1026', enrollmentNo: 'BTTC25O1026' },
  { id: 'S1027', name: 'DHRUV KUMAR CHAUDHARY', email: 'dhruv.chaudhary@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1027', enrollmentNo: 'BTTC25O1027' },
  { id: 'S1028', name: 'DHRUV RAJ DODIA', email: 'dhruv.dodia@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1028', enrollmentNo: 'BTTC25O1028' },
  { id: 'S1029', name: 'DIVY JAIN', email: 'divy.jain@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1029', enrollmentNo: 'BTTC25O1029' },
  { id: 'S1030', name: 'HARSH MAHASHABDE', email: 'harsh.mahashabde@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1030', enrollmentNo: 'BTTC25O1030' },
  { id: 'S1031', name: 'HARSHITA CHAUDHARY', email: 'harshita.chaudhary@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1031', enrollmentNo: 'BTTC25O1031' },
  { id: 'S1032', name: 'HEMA SINGH', email: 'hema.singh@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1032', enrollmentNo: 'BTTC25O1032' },
  { id: 'S1033', name: 'HIMANSHU SHAKYA', email: 'himanshu.shakya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1033', enrollmentNo: 'BTTC25O1033' },
  { id: 'S1034', name: 'JANVI PATIDAR', email: 'janvi.patidar@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1034', enrollmentNo: 'BTTC25O1034' },
  { id: 'S1035', name: 'KRATIK PATIL', email: 'kratik.patil@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1035', enrollmentNo: 'BTTC25O1035' },
  { id: 'S1037', name: 'KSHITIZ JAYASWAL', email: 'kshitiz.jayaswal@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1037', enrollmentNo: 'BTTC25O1037' },
  { id: 'S1037B', name: 'KRISHNAV SHIVHARE', email: 'krishnav.shivhare@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1037', enrollmentNo: 'BTTC25O1037' },
  { id: 'S1038', name: 'MAHI GUPTA', email: 'mahi.gupta@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1038', enrollmentNo: 'BTTC25O1038' },
  { id: 'S1039', name: 'MAHI JAIN', email: 'mahi.jain@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1039', enrollmentNo: 'BTTC25O1039' },
  { id: 'S1040', name: 'MOHD SHAFA AT KHAN', email: 'mohd.khan@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1040', enrollmentNo: 'BTTC25O1040' },
  { id: 'S1041', name: 'MOHINI RATHORE', email: 'mohini.rathore@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1041', enrollmentNo: 'BTTC25O1041' },
  { id: 'S1042', name: 'MOULIK GUPTA', email: 'moulik.gupta@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1042', enrollmentNo: 'BTTC25O1042' },
  { id: 'S1043', name: 'NIHARIKA NIRANJAN', email: 'niharika.niranjan@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1043', enrollmentNo: 'BTTC25O1043' },
  { id: 'S1044', name: 'NIKHIL DWIVEDI', email: 'nikhil.dwivedi@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1044', enrollmentNo: 'BTTC25O1044' },
  { id: 'S1045', name: 'PIYUSH CHAKRAWARTI', email: 'piyush.chakrawarti@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1045', enrollmentNo: 'BTTC25O1045' },
  { id: 'S1046', name: 'PIYUSH KUMAR', email: 'piyush.kumar@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1046', enrollmentNo: 'BTTC25O1046' },
  { id: 'S1047', name: 'PRAKHAR SHRIVASTAVA', email: 'prakhar.shrivastava@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1047', enrollmentNo: 'BTTC25O1047' },
  { id: 'S1048', name: 'PRANSHU JOHARI', email: 'pranshu.johari@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1048', enrollmentNo: 'BTTC25O1048' },
  { id: 'S1049', name: 'PRATHAM SEN', email: 'pratham.sen@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1049', enrollmentNo: 'BTTC25O1049' },
  { id: 'S1050', name: 'PRERNA MISHRA', email: 'prerna.mishra@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1050', enrollmentNo: 'BTTC25O1050' },
  { id: 'S1051', name: 'PRITHVI RAJ SHINDE', email: 'prithvi.shinde@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1051', enrollmentNo: 'BTTC25O1051' },
  { id: 'S1053', name: 'PRIYAL CHOUDHARY', email: 'priyal.choudhary@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1053', enrollmentNo: 'BTTC25O1053' },
  { id: 'S1054', name: 'PRIYANSHU GURDEKAR', email: 'priyanshu.gurdekar@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1054', enrollmentNo: 'BTTC25O1054' },
  { id: 'S1056', name: 'PRIYANSHU YADAV', email: 'priyanshu.yadav@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1056', enrollmentNo: 'BTTC25O1056' },
  { id: 'S1057', name: 'PURTI GUPTA', email: 'purti.gupta@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1057', enrollmentNo: 'BTTC25O1057' },
  { id: 'S1058', name: 'PUSHKAR CHAURASIYA', email: 'pushkar.chaurasiya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1058', enrollmentNo: 'BTTC25O1058' },
  { id: 'S1059', name: 'RADHIKA SIKARWAR', email: 'radhika.sikarwar@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1059', enrollmentNo: 'BTTC25O1059' },
  { id: 'S1060', name: 'RAJPAL GURJAR', email: 'rajpal.gurjar@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1060', enrollmentNo: 'BTTC25O1060' },
  { id: 'S1061', name: 'RISHIRAJ SINGH YADAV', email: 'rishiraj.yadav@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1061', enrollmentNo: 'BTTC25O1061' },
  { id: 'S1062', name: 'ROHIT PATEL', email: 'rohit.patel@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1062', enrollmentNo: 'BTTC25O1062' },
  { id: 'S1063', name: 'SAKSHI DUBEY', email: 'sakshi.dubey@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1063', enrollmentNo: 'BTTC25O1063' },
  { id: 'S1064', name: 'SAMPANN SHARMA', email: 'sampann.sharma@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1064', enrollmentNo: 'BTTC25O1064' },
  { id: 'S1065', name: 'SANDEEP NARWARIYA', email: 'sandeep.narwariya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1065', enrollmentNo: 'BTTC25O1065' },
  { id: 'S1066', name: 'SHUBH VERMA', email: 'shubh.verma@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1066', enrollmentNo: 'BTTC25O1066' },
  { id: 'S1067', name: 'SIDDHARTH NORKEY', email: 'siddharth.norkey@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1067', enrollmentNo: 'BTTC25O1067' },
  { id: 'S1068', name: 'SMITA SANODYA', email: 'smita.sanodya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1068', enrollmentNo: 'BTTC25O1068' },
  { id: 'S1069', name: 'SUMIT GARG', email: 'sumit.garg@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1069', enrollmentNo: 'BTTC25O1069' },
  { id: 'S1070', name: 'SWEETY BHADAURIYA', email: 'sweety.bhadauriya@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1070', enrollmentNo: 'BTTC25O1070' },
  { id: 'S1071', name: 'UNNATI GUPTA', email: 'unnati.gupta@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1071', enrollmentNo: 'BTTC25O1071' },
  { id: 'S1072', name: 'UNNATI SHARMA', email: 'unnati.sharma@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1072', enrollmentNo: 'BTTC25O1072' },
  { id: 'S1073', name: 'VED CHAUDHARY', email: 'ved.chaudhary@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1073', enrollmentNo: 'BTTC25O1073' },
  { id: 'S1074', name: 'VEDANT YADAV', email: 'vedant.yadav@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1074', enrollmentNo: 'BTTC25O1074' },
  { id: 'S1075', name: 'YASHRAJ SINGH BUNDELA', email: 'yashraj.bundela@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1075', enrollmentNo: 'BTTC25O1075' },
  { id: 'S1076', name: 'ADITYA SINGH RATHORE', email: 'aditya.rathore@student.edu', password: 'student123', role: 'student', department: 'CST', rollNumber: 'BTTC25O1076', enrollmentNo: 'BTTC25O1076' }
];

module.exports = users;
